### ISSUE TITLE
Integrate shipped project form

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/lecture-hall#34]
From https://docs.google.com/spreadsheets/d/1H3eWAH3trXgGudJgl_-bVHUe7jLgoJnQuBscMgirDGA/edit#gid=0

**Comment by MaxWofford** [comment]
This is being done in #37

**Comment by zachlatta** [comment]
Going to go ahead and close this because we've decided to focus on collecting weekly attendance over projects shipped.
