### ISSUE TITLE
Markdown in root directory of hackcamp/workshops are not rendered.

### ISSUE THREAD

**Issue by TheThirdOne** [hackclub/lecture-hall#5]
https://workshops.hackclub.com/CONTRIBUTING.md, https://workshops.hackclub.com/SLACK.md, https://workshops.hackclub.com/PREFACE.md, and https://workshops.hackclub.com/GUIDELINES.md do not exist despite being linked to and being hackcamp/workshops.

Note: https://workshops.hackclub.com/README.md does not exist either.

**Comment by MaxWofford** [comment]
Closed by #24
